# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: '10000tb'

google-ID: 'UA-112805664-1'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
#- {name: 'Miscellaneous', folder: 'pages', file: 'miscellaneous.html'}
- {name: 'OpenSource', folder: 'pages', file: 'opensource.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/xuehaohu'}
- {icon: 'github', link: 'https://github.com/10000TB'}
- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
